export const mockMenuItems: MenuItem[] = [
  // SALADS
  {
    id: "item-1",
    name: "Green Salad",
    description: "Fresh carrot, cucumber and radish salad",
    price: 175,
    categoryId: "cat-1",
    image:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 10,
    tags: ["vegetarian", "healthy"],
    tax: 13,
    costPrice: 70,
  },
  {
    id: "item-2",
    name: "Nepali Salad",
    description: "Traditional Nepali style mixed salad",
    price: 150,
    categoryId: "cat-1",
    image:
      "https://images.unsplash.com/photo-1546793665-c74683f339c1?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 10,
    tags: ["vegetarian"],
    tax: 13,
    costPrice: 60,
  },
  {
    id: "item-3",
    name: "Fruit Salad",
    description: "Seasonal fresh fruit salad",
    price: 300,
    categoryId: "cat-1",
    image:
      "https://images.unsplash.com/photo-1564093497595-593b96d80180?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 10,
    tags: ["healthy"],
    tax: 13,
    costPrice: 120,
  },

  // BREAKFAST
  {
    id: "item-4",
    name: "Bread Toast with Jam",
    description: "Toasted bread served with jam",
    price: 150,
    categoryId: "cat-2",
    image:
      "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 10,
    tax: 13,
    costPrice: 60,
  },
  {
    id: "item-5",
    name: "Bread Omelette",
    description: "Bread served with omelette",
    price: 160,
    categoryId: "cat-2",
    image:
      "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 12,
    tax: 13,
    costPrice: 70,
  },
  {
    id: "item-6",
    name: "Boiled Egg",
    description: "Fresh boiled egg",
    price: 50,
    categoryId: "cat-2",
    image:
      "https://images.unsplash.com/photo-1518569656558-1f25e69d93d7?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 5,
    tax: 13,
    costPrice: 20,
  },
  {
    id: "item-7",
    name: "American Breakfast",
    description: "Classic breakfast platter",
    price: 300,
    categoryId: "cat-2",
    image:
      "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 20,
    tax: 13,
    costPrice: 130,
  },
  {
    id: "item-8",
    name: "Aloo Paratha",
    description: "Stuffed potato flatbread",
    price: 80,
    categoryId: "cat-2",
    image:
      "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 15,
    tax: 13,
    costPrice: 35,
  },
  {
    id: "item-9",
    name: "Masala Omelette",
    description: "Spiced omelette with vegetables",
    price: 130,
    categoryId: "cat-2",
    image:
      "https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 10,
    tax: 13,
    costPrice: 50,
  },

  // SOUPS
  {
    id: "item-10",
    name: "Manchow Soup",
    description: "Hot and spicy Indo-Chinese soup",
    price: 175,
    categoryId: "cat-3",
    image:
      "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 15,
    tax: 13,
    costPrice: 70,
  },
  {
    id: "item-11",
    name: "Clear Soup",
    description: "Light and healthy clear soup",
    price: 175,
    categoryId: "cat-3",
    image:
      "https://plus.unsplash.com/premium_photo-1706003920144-ca73554a6801?q=80&w=872&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    isAvailable: true,
    status: "available",
    preparationTime: 15,
    tax: 13,
    costPrice: 70,
  },
  {
    id: "item-12",
    name: "Mushroom Soup",
    description: "Creamy mushroom soup",
    price: 160,
    categoryId: "cat-3",
    image:
      "https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 15,
    tax: 13,
    costPrice: 65,
  },
  {
    id: "item-13",
    name: "Hot and Sour Soup",
    description: "Spicy and tangy soup",
    price: 165,
    categoryId: "cat-3",
    image:
      "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 15,
    tax: 13,
    costPrice: 65,
  },

  // NOODLES
  {
    id: "item-14",
    name: "Keema Noodles",
    description: "Noodles with minced meat",
    price: 225,
    categoryId: "cat-4",
    image:
      "https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 20,
    tax: 13,
    costPrice: 90,
  },
  {
    id: "item-15",
    name: "Veg Noodles",
    description: "Stir-fried vegetable noodles",
    price: 150,
    categoryId: "cat-4",
    image:
      "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 20,
    tags: ["vegetarian"],
    tax: 13,
    costPrice: 60,
  },
  {
    id: "item-16",
    name: "Chicken Noodles",
    description: "Noodles with chicken pieces",
    price: 175,
    categoryId: "cat-4",
    image:
      "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 20,
    tax: 13,
    costPrice: 70,
  },
  {
    id: "item-17",
    name: "Schezwan Noodles",
    description: "Spicy schezwan flavored noodles",
    price: 180,
    categoryId: "cat-4",
    image:
      "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 20,
    tax: 13,
    costPrice: 75,
  },
  {
    id: "item-18",
    name: "Egg Noodles",
    description: "Noodles cooked with egg",
    price: 150,
    categoryId: "cat-4",
    image:
      "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 20,
    tax: 13,
    costPrice: 60,
  },
  {
    id: "item-19",
    name: "Mix Noodles",
    description: "Combination noodles with meat and vegetables",
    price: 300,
    categoryId: "cat-4",
    image:
      "https://images.unsplash.com/photo-1555126634-323283e090fa?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 20,
    tax: 13,
    costPrice: 120,
  },
  {
    id: "item-20",
    name: "Current Bowl Noodles",
    description: "Special house noodle bowl",
    price: 200,
    categoryId: "cat-4",
    image:
      "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 20,
    tax: 13,
    costPrice: 80,
  },

  // MOMO
  {
    id: "item-21",
    name: "Steam Momo",
    description: "Traditional steamed momo",
    price: 120,
    categoryId: "cat-5",
    image:
      "https://plus.unsplash.com/premium_photo-1671547329182-deaf1c94263e?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    isAvailable: true,
    status: "available",
    preparationTime: 15,
    tax: 13,
    costPrice: 50,
  },
  {
    id: "item-22",
    name: "Fry Momo",
    description: "Deep fried momo",
    price: 150,
    categoryId: "cat-5",
    image:
      "https://images.unsplash.com/photo-1738608084602-f9543952188e?q=80&w=872&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    isAvailable: true,
    status: "available",
    preparationTime: 15,
    tax: 13,
    costPrice: 60,
  },
  {
    id: "item-23",
    name: "Chilly Momo",
    description: "Spicy chilly momo",
    price: 175,
    categoryId: "cat-5",
    image: "https://boliya.in/wp-content/uploads/2025/05/3-9.png",
    isAvailable: true,
    status: "available",
    preparationTime: 20,
    tax: 13,
    costPrice: 70,
  },
  {
    id: "item-24",
    name: "Jhol Momo",
    description: "Momo served in spicy broth",
    price: 150,
    categoryId: "cat-5",
    image:
      "https://images.news18.com/ibnlive/uploads/2025/12/jhol-momos-1-2025-12-caa875266cb632b781ff7464c9ad3f5d-4x3.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 20,
    tax: 13,
    costPrice: 60,
  },
  {
    id: "item-25",
    name: "Kothey Momo",
    description: "Pan-fried momo",
    price: 175,
    categoryId: "cat-5",
    image:
      "https://foodenginepokhara.com/wp-content/uploads/2025/05/kothey-momo.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 20,
    tax: 13,
    costPrice: 70,
  },
  {
    id: "item-26",
    name: "Sadheko Momo",
    description: "Spicy mixed momo",
    price: 175,
    categoryId: "cat-5",
    image:
      "https://d1w7312wesee68.cloudfront.net/apXnRLlS8wgSduDjUmh6wdvlUJJ7TXy2S5yKAjR9Hk8/resize:fit:720:720/plain/s3://toasttab/restaurants/restaurant-207226000000000000/menu/items/2/item-1200000013758324302_1777330497.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 20,
    tax: 13,
    costPrice: 70,
  },

  // THUKPA
  // THUKPA
  {
    id: "item-27",
    name: "Veg Thukpa",
    description: "Vegetable noodle soup",
    price: 175,
    categoryId: "cat-6",
    image:
      "https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 20,
    tax: 13,
    costPrice: 70,
  },
  {
    id: "item-28",
    name: "Chicken Veg Thukpa",
    description: "Chicken and vegetable thukpa",
    price: 200,
    categoryId: "cat-6",
    image:
      "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 20,
    tax: 13,
    costPrice: 80,
  },
  {
    id: "item-29",
    name: "Mix Thukpa",
    description: "Mixed meat and vegetable thukpa",
    price: 250,
    categoryId: "cat-6",
    image:
      "https://images.unsplash.com/photo-1555126634-323283e090fa?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 20,
    tax: 13,
    costPrice: 100,
  },

  // FRIED RICE
  {
    id: "item-30",
    name: "Veg Fried Rice",
    description: "Stir fried rice with vegetables",
    price: 180,
    categoryId: "cat-10",
    image:
      "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80",
    preparationTime: 20,
    tax: 13,
    costPrice: 75,
    status: "available",
    isAvailable: true,
    tags: ["vegetarian"],
  },
  {
    id: "item-31",
    name: "Egg Fried Rice",
    description: "Fried rice with egg",
    price: 220,
    categoryId: "cat-10",
    image:
      "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80",
    preparationTime: 20,
    tax: 13,
    costPrice: 90,
    status: "available",
    isAvailable: true,
  },
  {
    id: "item-32",
    name: "Chicken Fried Rice",
    description: "Fried rice with chicken and egg",
    price: 250,
    categoryId: "cat-10",
    image:
      "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80",
    preparationTime: 22,
    tax: 13,
    costPrice: 110,
    status: "available",
    isAvailable: true,
  },
  {
    id: "item-33",
    name: "Mixed Fried Rice",
    description: "Mixed meat fried rice",
    price: 350,
    categoryId: "cat-10",
    image:
      "https://images.unsplash.com/photo-1555126634-323283e090fa?auto=format&fit=crop&w=800&q=80",
    preparationTime: 25,
    tax: 13,
    costPrice: 150,
    status: "available",
    isAvailable: true,
  },
  {
    id: "item-34",
    name: "Seafood Fried Rice",
    description: "Seafood fried rice with prawns and fish",
    price: 450,
    categoryId: "cat-10",
    image:
      "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=800&q=80",
    preparationTime: 25,
    tax: 13,
    costPrice: 190,
    status: "available",
    isAvailable: true,
  },
  // SADHEKO
  {
    id: "item-35",
    name: "Wai Wai Sadheko",
    price: 120,
    description: "Spicy Wai Wai noodle salad",
    categoryId: "cat-11",
    image:
      "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80",
    preparationTime: 10,
    tax: 13,
    costPrice: 45,
    status: "available",
    isAvailable: true,
  },
  {
    id: "item-36",
    name: "Chicken Sadheko",
    description: "Boiled or fried chicken mixed with Nepali spices",
    price: 275,
    categoryId: "cat-11",
    image:
      "https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=800&q=80",
    preparationTime: 20,
    tax: 13,
    costPrice: 120,
    status: "available",
    isAvailable: true,
  },
  {
    id: "item-37",
    name: "Mix Wai Wai Sadheko",
    price: 200,
    description: "Mixed Wai Wai salad with vegetables and spices",
    categoryId: "cat-11",
    image:
      "https://images.unsplash.com/photo-1555126634-323283e090fa?auto=format&fit=crop&w=800&q=80",
    preparationTime: 15,
    tax: 13,
    costPrice: 90,
    status: "available",
    isAvailable: true,
  },
  {
    id: "item-38",
    name: "Peanut Sadheko",
    price: 190,
    description: "Spicy roasted peanut salad",
    categoryId: "cat-11",
    image:
      "https://images.unsplash.com/photo-1508747703725-719777637510?auto=format&fit=crop&w=800&q=80",
    preparationTime: 10,
    tax: 13,
    costPrice: 70,
    status: "available",
    isAvailable: true,
  },
  {
    id: "item-39",
    name: "Bhatmas Sadheko",
    price: 200,
    description: "Spiced roasted soybean salad",
    categoryId: "cat-11",
    image:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    preparationTime: 12,
    tax: 13,
    costPrice: 80,
    status: "available",
    isAvailable: true,
  },
    // CHICKEN & SEAFOOD
  {
    id: "item-48",
    name: "Chicken Chilli",
    description: "Spicy stir-fried chicken with onion and capsicum",
    price: 300,
    categoryId: "cat-12",
    image:
      "https://images.unsplash.com/photo-1603360946369-dc9bb6258143?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 20,
    tags: ["spicy", "non-veg"],
    tax: 13,
    costPrice: 130,
  },
  {
    id: "item-49",
    name: "Chicken 65",
    description: "Crispy South Indian style spicy chicken",
    price: 375,
    categoryId: "cat-12",
    image:
      "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 22,
    tags: ["spicy", "non-veg"],
    tax: 13,
    costPrice: 160,
  },
  {
    id: "item-50",
    name: "Chicken Fry",
    description: "Deep fried seasoned chicken pieces",
    price: 300,
    categoryId: "cat-12",
    image:
      "https://images.unsplash.com/photo-1527477396000-e27163b481c2?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 18,
    tags: ["fried", "non-veg"],
    tax: 13,
    costPrice: 125,
  },
  {
    id: "item-51",
    name: "Chicken Gravy",
    description: "Chicken cooked in rich house gravy",
    price: 350,
    categoryId: "cat-12",
    image:
      "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 25,
    tags: ["gravy", "non-veg"],
    tax: 13,
    costPrice: 150,
  },
  {
    id: "item-52",
    name: "Crispy Chicken",
    description: "Crunchy crispy chicken with special seasoning",
    price: 375,
    categoryId: "cat-12",
    image:
      "https://images.unsplash.com/photo-1562967916-eb82221dfb92?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 20,
    tags: ["crispy", "non-veg"],
    tax: 13,
    costPrice: 155,
  },
  {
    id: "item-53",
    name: "Chicken Cheese Ball",
    description: "Chicken and cheese stuffed fried balls",
    price: 450,
    categoryId: "cat-12",
    image:
      "https://images.unsplash.com/photo-1625944230945-1b7dd3b949ab?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 25,
    tags: ["cheese", "non-veg"],
    tax: 13,
    costPrice: 190,
  },
  {
    id: "item-54",
    name: "Chicken Popcorn",
    description: "Bite-sized crispy popcorn chicken",
    price: 250,
    categoryId: "cat-12",
    image:
      "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 15,
    tags: ["fried", "non-veg"],
    tax: 13,
    costPrice: 100,
  },
  {
    id: "item-55",
    name: "Timur Chicken",
    description: "Chicken tossed with Nepali timur spices",
    price: 350,
    categoryId: "cat-12",
    image:
      "https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 22,
    tags: ["timur", "non-veg"],
    tax: 13,
    costPrice: 145,
  },
  {
    id: "item-56",
    name: "Chicken Choila",
    description: "Traditional Nepali spicy grilled chicken",
    price: 350,
    categoryId: "cat-12",
    image:
      "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 20,
    tags: ["choila", "non-veg"],
    tax: 13,
    costPrice: 145,
  },
  {
    id: "item-57",
    name: "Dragon Chicken",
    description: "Hot and sweet Indo-Chinese chicken",
    price: 400,
    categoryId: "cat-12",
    image:
      "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 22,
    tags: ["spicy", "non-veg"],
    tax: 13,
    costPrice: 170,
  },
  {
    id: "item-58",
    name: "Sausage",
    description: "Available in boiled, fried or chilli style",
    price: 275,
    categoryId: "cat-12",
    image:
      "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 15,
    tags: ["snacks"],
    tax: 13,
    costPrice: 110,
  },
  {
    id: "item-59",
    name: "Chicken Lollipop",
    description: "Crispy chicken lollipop with dipping sauce",
    price: 350,
    categoryId: "cat-12",
    image:
      "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 20,
    tags: ["fried", "non-veg"],
    tax: 13,
    costPrice: 150,
  },
  {
    id: "item-60",
    name: "Mix Seafood Chilli",
    description: "Mixed seafood tossed in spicy chilli sauce",
    price: 475,
    categoryId: "cat-12",
    image:
      "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 25,
    tags: ["seafood", "spicy"],
    tax: 13,
    costPrice: 220,
  },
    // PLATTERS
  {
    id: "item-61",
    name: "Local Vibes Platter",
    description:
      "Momo, chicken lollipop, sausage, burger, chicken chilli and chicken fried rice",
    price: 725,
    categoryId: "cat-13",
    image:
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 35,
    tags: ["sharing", "special"],
    tax: 13,
    costPrice: 340,
  },
  {
    id: "item-62",
    name: "Special Platter",
    description: "Momo, sausage chilli, chicken fry, lollipop and noodles",
    price: 525,
    categoryId: "cat-13",
    image:
      "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 30,
    tags: ["sharing", "special"],
    tax: 13,
    costPrice: 250,
  },
  {
    id: "item-63",
    name: "Momo Platter",
    description: "Steam Momo, Sadeko, Fry, Chilly and Kothey",
    price: 425,
    categoryId: "cat-13",
    isAvailable: true,
    status: "available",
    preparationTime: 5,
    tax: 13,
    costPrice: 60,
    image:
      "https://images.unsplash.com/photo-1626500155537-93690c24099e?auto=format&fit=crop&w=800&q=80",
  },
  // VEG STARTERS
  {
    id: "item-40",
    name: "Sweet Corn",
    price: 150,
    description: "Boiled sweet corn",
    categoryId: "cat-14",
    image:
      "https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=800&q=80",
    preparationTime: 10,
    tax: 13,
    costPrice: 60,
    status: "available",
    isAvailable: true,
  },
  {
    id: "item-41",
    name: "Corn Salt & Pepper",
    price: 225,
    description: "Sweet corn tossed with salt and pepper",
    categoryId: "cat-14",
    image:
      "https://images.unsplash.com/photo-1619719015141-8f5c1b8dfedf?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    preparationTime: 15,
    tax: 13,
    costPrice: 90,
    status: "available",
    isAvailable: true,
  },
  {
    id: "item-42",
    name: "French Fries",
    price: 175,
    description: "Crispy golden french fries",
    categoryId: "cat-14",
    image:
      "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=800&q=80",
    preparationTime: 12,
    tax: 13,
    costPrice: 70,
    status: "available",
    isAvailable: true,
  },
  {
    id: "item-43",
    name: "Mushroom Chilli",
    price: 225,
    description: "Spicy chilli mushroom",
    categoryId: "cat-14",
    image:
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80",
    preparationTime: 15,
    tax: 13,
    costPrice: 90,
    status: "available",
    isAvailable: true,
  },
  {
    id: "item-44",
    name: "Paneer Chilli",
    price: 250,
    description: "Paneer tossed in spicy chilli sauce",
    categoryId: "cat-14",
    image:
      "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80",
    preparationTime: 18,
    tax: 13,
    costPrice: 100,
    status: "available",
    isAvailable: true,
  },
  {
    id: "item-45",
    name: "Potato Chilli",
    price: 225,
    description: "Spicy chilli potato",
    categoryId: "cat-14",
    image:
      "https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=800&q=80",
    preparationTime: 15,
    tax: 13,
    costPrice: 80,
    status: "available",
    isAvailable: true,
  },
  {
    id: "item-46",
    name: "Veg Satay",
    price: 250,
    description: "Grilled vegetable satay skewers",
    categoryId: "cat-14",
    image:
      "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    preparationTime: 20,
    tax: 13,
    costPrice: 100,
    status: "available",
    isAvailable: true,
  },
  {
    id: "item-47",
    name: "Mustang Aloo",
    price: 225,
    description: "Traditional Nepali spicy potato dish",
    categoryId: "cat-14",
    image:
      "https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=800&q=80",
    preparationTime: 15,
    tax: 13,
    costPrice: 90,
    status: "available",
    isAvailable: true,
  },

  // TEA & COFFEE
  {
    id: "item-64",
    name: "Black Tea",
    description: "Freshly brewed black tea",
    price: 20,
    categoryId: "cat-16",
    isAvailable: true,
    status: "available",
    preparationTime: 5,
    tax: 13,
    costPrice: 8,
    image:
      "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "item-65",
    name: "Lemon Tea",
    description: "Refreshing tea infused with lemon",
    price: 25,
    categoryId: "cat-16",
    isAvailable: true,
    status: "available",
    preparationTime: 5,
    tax: 13,
    costPrice: 10,
    image:
      "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "item-66",
    name: "Milk Tea",
    description: "Traditional milk tea",
    price: 35,
    categoryId: "cat-16",
    isAvailable: true,
    status: "available",
    preparationTime: 5,
    tax: 13,
    costPrice: 12,
    image:
      "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "item-67",
    name: "Masala Tea",
    description: "Spiced milk tea with aromatic herbs",
    price: 50,
    categoryId: "cat-16",
    isAvailable: true,
    status: "available",
    preparationTime: 7,
    tax: 13,
    costPrice: 18,
    image:
      "https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "item-68",
    name: "Black Coffee",
    description: "Rich black coffee",
    price: 50,
    categoryId: "cat-16",
    isAvailable: true,
    status: "available",
    preparationTime: 5,
    tax: 13,
    costPrice: 20,
    image:
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "item-69",
    name: "Milk Coffee",
    description: "Creamy milk coffee",
    price: 80,
    categoryId: "cat-16",
    isAvailable: true,
    status: "available",
    preparationTime: 7,
    tax: 13,
    costPrice: 30,
    image:
      "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80",
  },

  // SOFT DRINKS
  {
    id: "item-70",
    name: "Slice",
    description: "Mango flavored soft drink",
    price: 75,
    categoryId: "cat-17",
    isAvailable: true,
    status: "available",
    preparationTime: 1,
    tax: 13,
    costPrice: 50,
    image:
      "https://5.imimg.com/data5/PX/IG/WF/SELLER-78937821/250ml-tropicana-slice-mango-drink.jpg",
  },
  {
    id: "item-71",
    name: "Mountain Dew",
    description: "Citrus flavored carbonated soft drink",
    price: 75,
    categoryId: "cat-17",
    isAvailable: true,
    status: "available",
    preparationTime: 1,
    tax: 13,
    costPrice: 50,
    image:
      "https://prod-spinneys-cdn-new.azureedge.net/media/cache/d1/59/d159a16938fbd26f257e0f0e133df24a.jpg",
  },
  {
    id: "item-72",
    name: "Sprite",
    description: "Lemon-lime soft drink",
    price: 75,
    categoryId: "cat-17",
    isAvailable: true,
    status: "available",
    preparationTime: 1,
    tax: 13,
    costPrice: 50,
    image:
      "https://hebmx.vtexassets.com/arquivos/ids/627293/577178-1663033324.jpg?v=638497816220830000",
  },
  {
    id: "item-73",
    name: "Coca-Cola",
    description: "Classic cola soft drink",
    price: 75,
    categoryId: "cat-17",
    isAvailable: true,
    status: "available",
    preparationTime: 1,
    tax: 13,
    costPrice: 50,
    image:
      "https://hebmx.vtexassets.com/arquivos/ids/627293/577178-1663033324.jpg?v=638497816220830000",
  },
  {
    id: "item-74",
    name: "Fanta",
    description: "Orange flavored soft drink",
    price: 75,
    categoryId: "cat-17",
    isAvailable: true,
    status: "available",
    preparationTime: 1,
    tax: 13,
    costPrice: 50,
    image:
      "https://www.osterlenbryggarna.se/wp-content/uploads/2019/01/fanta-25cl.jpg",
  },
  {
    id: "item-75",
    name: "Red Bull (Regular)",
    description: "Classic Red Bull energy drink",
    price: 150,
    categoryId: "cat-17",
    isAvailable: true,
    status: "available",
    preparationTime: 1,
    tax: 13,
    costPrice: 100,
    image:
      "https://media.rainpos.com/3226/71r5aajatcl_sl1500__20180628133009.jpg",
  },
  {
    id: "item-76",
    name: "Red Bull (Blue Edition)",
    description: "Blue edition energy drink",
    price: 250,
    categoryId: "cat-17",
    isAvailable: true,
    status: "available",
    preparationTime: 1,
    tax: 13,
    costPrice: 180,
    image: "https://m.media-amazon.com/images/I/61ptJdBOUsL.jpg",
  },
  {
    id: "item-77",
    name: "Real Juice",
    description: "Packed fruit juice",
    price: 125,
    categoryId: "cat-17",
    isAvailable: true,
    status: "available",
    preparationTime: 1,
    tax: 13,
    costPrice: 80,
    image:
      "https://img.drz.lazcdn.com/g/kf/Se40a95af06a54c09a31edf50741337d38.jpg_720x720q80.jpg_.webp",
  },

  // MOCKTAILS
  {
    id: "item-78",
    name: "Banana Lassi",
    description: "Sweet yogurt drink blended with banana",
    price: 120,
    categoryId: "cat-18",
    isAvailable: true,
    status: "available",
    preparationTime: 5,
    tax: 13,
    costPrice: 50,
    image:
      "https://media.istockphoto.com/id/1324085825/photo/glass-of-fresh-homemade-indian-lassi-drink-made-of-ripe-banana-fruit-and-yogurt-served-with.jpg?s=612x612&w=0&k=20&c=x07kAjgurApe_Wmf2gutmKl0RHN1hn96CXQsUvHqRT8=",
  },
  {
    id: "item-79",
    name: "Plain Lassi",
    description: "Traditional chilled yogurt drink",
    price: 100,
    categoryId: "cat-18",
    isAvailable: true,
    status: "available",
    preparationTime: 5,
    tax: 13,
    costPrice: 40,
    image:
      "https://tiimg.tistatic.com/fp/5/007/789/excellent-sterilized-original-milk-flavoring-tasty-sweet-white-lassi--010.jpg",
  },
  {
    id: "item-80",
    name: "Virgin Mojito",
    description: "Refreshing mint and lime mocktail",
    price: 170,
    categoryId: "cat-18",
    isAvailable: true,
    status: "available",
    preparationTime: 7,
    tax: 13,
    costPrice: 70,
    image:
      "https://t3.ftcdn.net/jpg/15/23/26/76/360_F_1523267674_kyREEQ9uQL35dFeQxYRGwOroZAoVvGwE.jpg",
  },
  {
    id: "item-81",
    name: "Iced Peach Tea",
    description: "Chilled peach flavored tea",
    price: 150,
    categoryId: "cat-18",
    isAvailable: true,
    status: "available",
    preparationTime: 5,
    tax: 13,
    costPrice: 60,
    image:
      "https://mrpuffs.com/cdn/shop/files/MrPuffs_Theglace_Peche.jpg?v=1713886905",
  },
  {
    id: "item-82",
    name: "Cold Coffee",
    description: "Chilled creamy coffee beverage",
    price: 120,
    categoryId: "cat-18",
    isAvailable: true,
    status: "available",
    preparationTime: 5,
    tax: 13,
    costPrice: 50,
    image:
      "https://itallianbox.com/wp-content/uploads/2025/06/cold-coffe-2.png",
  },
  {
    id: "item-83",
    name: "Iced Lemon Tea",
    description: "Refreshing chilled lemon tea",
    price: 120,
    categoryId: "cat-18",
    isAvailable: true,
    status: "available",
    preparationTime: 5,
    tax: 13,
    costPrice: 50,
    image:
      "https://leelalicious.com/wp-content/uploads/2016/04/Thai-Lemon-Iced-Tea-Recipe.jpg",
  },
  {
    id: "item-84",
    name: "Watermelon Refresher",
    description: "Fresh watermelon cooler",
    price: 150,
    categoryId: "cat-18",
    isAvailable: true,
    status: "available",
    preparationTime: 5,
    tax: 13,
    costPrice: 60,
    image:
      "https://fishbowl.s3.amazonaws.com/recipes/94_watermelon-refhresher_web.jpg",
  },

  // 8848 WHISKY
  {
    id: "item-85",
    name: "8848 (60ml)",
    description: "Premium Nepalese whisky",
    price: 225,
    categoryId: "cat-15",
    image:
      "https://static-01.daraz.com.np/p/2038a687f4d62f40c6a1ba018bce49ca.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 90,
  },
  {
    id: "item-86",
    name: "8848 (90ml)",
    description: "Premium Nepalese whisky",
    price: 450,
    categoryId: "cat-15",
    image:
      "https://static-01.daraz.com.np/p/2038a687f4d62f40c6a1ba018bce49ca.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 180,
  },
  {
    id: "item-87",
    name: "8848 (180ml)",
    description: "Premium Nepalese whisky",
    price: 825,
    categoryId: "cat-15",
    image:
      "https://static-01.daraz.com.np/p/2038a687f4d62f40c6a1ba018bce49ca.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 330,
  },
  {
    id: "item-88",
    name: "8848 (360ml)",
    description: "Premium Nepalese whisky",
    price: 825,
    categoryId: "cat-15",
    image:
      "https://static-01.daraz.com.np/p/2038a687f4d62f40c6a1ba018bce49ca.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 330,
  },
  {
    id: "item-89",
    name: "8848 (Full Bottle)",
    description: "Premium Nepalese whisky",
    price: 3200,
    categoryId: "cat-15",
    image:
      "https://static-01.daraz.com.np/p/2038a687f4d62f40c6a1ba018bce49ca.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 1300,
  },

  // Black Oak WHISKY
  {
    id: "item-90",
    name: "Black Oak (60ml)",
    description: "Smooth blended whisky",
    price: 150,
    categoryId: "cat-15",
    image: "https://darumandu.com/storage/product/2025-01-04-6779589d8980d.png",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 60,
  },
  {
    id: "item-91",
    name: "Black Oak (90ml)",
    description: "Smooth blended whisky",
    price: 290,
    categoryId: "cat-15",
    image: "https://darumandu.com/storage/product/2025-01-04-6779589d8980d.png",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 120,
  },
  {
    id: "item-92",
    name: "Black Oak (180ml)",
    description: "Smooth blended whisky",
    price: 573,
    categoryId: "cat-15",
    image: "https://darumandu.com/storage/product/2025-01-04-6779589d8980d.png",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 230,
  },
  {
    id: "item-93",
    name: "Black Oak (360ml)",
    description: "Smooth blended whisky",
    price: 1150,
    categoryId: "cat-15",
    image: "https://darumandu.com/storage/product/2025-01-04-6779589d8980d.png",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 460,
  },
  {
    id: "item-94",
    name: "Black Oak (Full Bottle)",
    description: "Smooth blended whisky",
    price: 2450,
    categoryId: "cat-15",
    image: "https://darumandu.com/storage/product/2025-01-04-6779589d8980d.png",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 980,
  },

  // Kukuri Rum
  {
    id: "item-95",
    name: "Kukuri Rum (60ml)",
    description: "Classic Nepalese dark rum",
    price: 280,
    categoryId: "cat-15",
    image:
      "https://static-01.daraz.com.np/p/3da199cec3db5c2d011a9f22efafe912.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 110,
  },
  {
    id: "item-96",
    name: "Kukuri Rum (90ml)",
    description: "Classic Nepalese dark rum",
    price: 450,
    categoryId: "cat-15",
    image:
      "https://static-01.daraz.com.np/p/3da199cec3db5c2d011a9f22efafe912.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 180,
  },
  {
    id: "item-97",
    name: "Kukuri Rum (180ml)",
    description: "Classic Nepalese dark rum",
    price: 820,
    categoryId: "cat-15",
    image:
      "https://static-01.daraz.com.np/p/3da199cec3db5c2d011a9f22efafe912.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 330,
  },
  {
    id: "item-98",
    name: "Kukuri Rum (360ml)",
    description: "Classic Nepalese dark rum",
    price: 1625,
    categoryId: "cat-15",
    image:
      "https://static-01.daraz.com.np/p/3da199cec3db5c2d011a9f22efafe912.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 650,
  },
  {
    id: "item-99",
    name: "Kukuri Rum (Full Bottle)",
    description: "Classic Nepalese dark rum",
    price: 3200,
    categoryId: "cat-15",
    image:
      "https://static-01.daraz.com.np/p/3da199cec3db5c2d011a9f22efafe912.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 1280,
  },

  // Signature Whisky (Autocompleted the missing fields structure from your snippet cutoff)
  {
    id: "item-100",
    name: "Signature Whisky",
    description: "Premium blended whisky",
    price: 350,
    categoryId: "cat-15",
    image:
      "https://static-01.daraz.com.np/p/d1e9eeae407a1eae8cb3d356aa1ee17a.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 140,
  },
  {
    id: "item-101",
    name: "Signature Whisky (90ml)",
    price: 575,
    description: "Premium Indian whisky",
    categoryId: "cat-15",
    image:
      "https://static-01.daraz.com.np/p/d1e9eeae407a1eae8cb3d356aa1ee17a.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 230,
  },
  {
    id: "item-102",
    name: "Signature Whisky (180ml)",
    price: 965,
    description: "Premium Indian whisky",
    categoryId: "cat-15",
    image:
      "https://static-01.daraz.com.np/p/d1e9eeae407a1eae8cb3d356aa1ee17a.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 385,
  },
  {
    id: "item-103",
    name: "Signature Whisky (360ml)",
    price: 1890,
    description: "Premium Indian whisky",
    categoryId: "cat-15",
    image:
      "https://static-01.daraz.com.np/p/d1e9eeae407a1eae8cb3d356aa1ee17a.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 756,
  },
  {
    id: "item-104",
    name: "Signature Whisky (Full Bottle)",
    price: 3700,
    description: "Premium Indian whisky",
    categoryId: "cat-15",
    image:
      "https://static-01.daraz.com.np/p/d1e9eeae407a1eae8cb3d356aa1ee17a.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 1480,
  },

  // Old Durbar
  {
    id: "item-105",
    name: "Old Durbar Whisky (60ml)",
    price: 325,
    description: "Premium Nepalese whisky",
    categoryId: "cat-15",
    image:
      "https://img.fatafatsewa.com/products/939/old-durbar-750-ml-price-in-nepal.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 130,
  },
  {
    id: "item-106",
    name: "Old Durbar Whisky (90ml)",
    price: 650,
    description: "Premium Nepalese whisky",
    categoryId: "cat-15",
    image:
      "https://img.fatafatsewa.com/products/939/old-durbar-750-ml-price-in-nepal.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 260,
  },
  {
    id: "item-107",
    name: "Old Durbar Whisky (180ml)",
    price: 1230,
    description: "Premium Nepalese whisky",
    categoryId: "cat-15",
    image:
      "https://img.fatafatsewa.com/products/939/old-durbar-750-ml-price-in-nepal.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 492,
  },
  {
    id: "item-108",
    name: "Old Durbar Whisky (360ml)",
    price: 2400,
    description: "Premium Nepalese whisky",
    categoryId: "cat-15",
    image:
      "https://img.fatafatsewa.com/products/939/old-durbar-750-ml-price-in-nepal.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 960,
  },
  {
    id: "item-109",
    name: "Old Durbar Whisky (Full Bottle)",
    price: 4950,
    description: "Premium Nepalese whisky",
    categoryId: "cat-15",
    image:
      "https://img.fatafatsewa.com/products/939/old-durbar-750-ml-price-in-nepal.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 1980,
  },

  // Cigarettes
  {
    id: "item-110",
    name: "Shikhar Ice",
    description: "Pack of Shikhar Ice cigarettes",
    price: 25,
    categoryId: "cat-20",
    image:
      "https://hungerend.com/wp-content/uploads/2022/05/shikhar-ice-pcs.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 0,
    tax: 13,
    costPrice: 18,
  },
  {
    id: "item-111",
    name: "Surya Red Light",
    description: "Pack of Surya Red Light cigarettes",
    price: 30,
    categoryId: "cat-20",
    image:
      "https://hungerend.com/wp-content/uploads/2022/03/surya-red-pcs-min.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 0,
    tax: 13,
    costPrice: 22,
  },

  // Gorkha Beer
  {
    id: "item-112",
    name: "Gorkha Beer (330ml)",
    description: "Refreshing Nepalese lager beer",
    price: 250,
    categoryId: "cat-21",
    image:
      "https://fulltimeexplorer.com/wp-content/uploads/2020/10/nepali-beers-gorka-premium-and-strong.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 100,
  },
  {
    id: "item-113",
    name: "Gorkha Beer (500ml)",
    description: "Refreshing Nepalese lager beer",
    price: 500,
    categoryId: "cat-21",
    image:
      "https://fulltimeexplorer.com/wp-content/uploads/2020/10/nepali-beers-gorka-premium-and-strong.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 200,
  },

  // Tuborg Strong
  {
    id: "item-114",
    name: "Tuborg Strong (330ml)",
    description: "Strong premium lager beer",
    price: 275,
    categoryId: "cat-21",
    image: "https://ferdico.it/img-prodotti/8007950016244.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 110,
  },
  {
    id: "item-115",
    name: "Tuborg Strong (500ml)",
    description: "Strong premium lager beer",
    price: 500,
    categoryId: "cat-21",
    image: "https://ferdico.it/img-prodotti/8007950016244.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 200,
  },

  // Tuborg Gold
  {
    id: "item-116",
    name: "Tuborg Gold (330ml)",
    description: "Premium gold lager beer",
    price: 275,
    categoryId: "cat-21",
    image:
      "https://static-01.daraz.com.np/p/0fc94b19bce1812fd0f475426d7a65de.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 110,
  },
  {
    id: "item-117",
    name: "Tuborg Gold (500ml)",
    description: "Premium gold lager beer",
    price: 550,
    categoryId: "cat-21",
    image:
      "https://static-01.daraz.com.np/p/0fc94b19bce1812fd0f475426d7a65de.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 220,
  },

  // Barahsinghe Beer
  {
    id: "item-118",
    name: "Barahsinghe Beer (330ml)",
    description: "Craft beer with rich flavor",
    price: 325,
    categoryId: "cat-21",
    image:
      "https://static-01.daraz.com.np/p/32ce4f5bb2f238136116d31d7a47a4b5.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 130,
  },
  {
    id: "item-119",
    name: "Barahsinghe Beer (500ml)",
    description: "Craft beer with rich flavor",
    price: 600,
    categoryId: "cat-21",
    image:
      "https://static-01.daraz.com.np/p/32ce4f5bb2f238136116d31d7a47a4b5.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 2,
    tax: 13,
    costPrice: 240,
  },
  // Hookah
  {
    id: "item-120",
    name: "Pan Mint Hookah",
    description: "Refreshing pan mint flavored hookah",
    price: 350,
    categoryId: "cat-22",
    image:
      "https://iconhookah.com/cdn/shop/products/moze-breeze-two-hookah-wavy-blue_800x.jpg?v=1644428737",
    isAvailable: true,
    status: "available",
    preparationTime: 5,
    tax: 13,
    costPrice: 140,
  },
  {
    id: "item-121",
    name: "Local Vibes Special Hookah",
    description: "House special signature hookah flavor",
    price: 450,
    categoryId: "cat-22",
    image:
      "https://images-eu.ssl-images-amazon.com/images/I/61OQTDpuyuL._AC_UL495_SR435,495_.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 5,
    tax: 13,
    costPrice: 180,
  },
  {
    id: "item-122",
    name: "Hookah Refill",
    description: "Refill for existing hookah setup",
    price: 250,
    categoryId: "cat-22",
    image:
      "https://shopdop.in/cdn/shop/articles/Hookah_Bowl_Filling.jpg?v=1658320959",
    isAvailable: true,
    status: "available",
    preparationTime: 3,
    tax: 13,
    costPrice: 100,
  },
  {
    id: "item-123",
    name: "Hookah Coil",
    description: "Replacement hookah charcoal coil",
    price: 50,
    categoryId: "cat-22",
    image:
      "https://420shop.nl/media/catalog/product/cache/72f5e12cc3bd3881fe4970b99275a0da/w/a/waterpijp-kooltjes_1.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 1,
    tax: 13,
    costPrice: 20,
  },
  //Buff and Pork
  {
    id: "item-124",
    name: "Buff Sukuti",
    description:
      "Traditional Nepali buffalo meat jerky served with local spices",
    price: 380,
    categoryId: "cat-9",
    isAvailable: true,
    status: "available",
    preparationTime: 15,
    tags: ["buff", "spicy"],
    tax: 13,
    costPrice: 160,
    image:
      "https://barmandoo.com.np/products-images/6579beb1cb1011bbfe025cd7_1714853523334.png",
  },

  {
    id: "item-125",
    name: "Buff Sadeko",
    description:
      "Spicy marinated buffalo meat mixed with onion, chili and herbs",
    price: 350,
    categoryId: "cat-9",
    isAvailable: true,
    status: "available",
    preparationTime: 15,
    tags: ["buff", "sadeko"],
    tax: 13,
    costPrice: 145,
    image:
      "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
  },

  {
    id: "item-126",
    name: "Buff Chilly",
    description:
      "Buffalo meat stir-fried with onions, capsicum and spicy sauce",
    price: 300,
    categoryId: "cat-9",
    isAvailable: true,
    status: "available",
    preparationTime: 18,
    tags: ["buff", "chilly"],
    tax: 13,
    costPrice: 130,
    image:
      "https://images.unsplash.com/photo-1603360946369-dc9bb6258143?auto=format&fit=crop&w=800&q=80",
  },

  {
    id: "item-127",
    name: "Pork Sadeko",
    description: "Spicy Nepali-style pork salad with herbs and local spices",
    price: 350,
    categoryId: "cat-9",
    isAvailable: true,
    status: "available",
    preparationTime: 15,
    tags: ["pork", "sadeko"],
    tax: 13,
    costPrice: 145,
    image:
      "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
  },

  {
    id: "item-128",
    name: "Pork Gravy",
    description: "Tender pork cooked in rich Nepali-style gravy",
    price: 375,
    categoryId: "cat-9",
    isAvailable: true,
    status: "available",
    preparationTime: 20,
    tags: ["pork", "gravy"],
    tax: 13,
    costPrice: 160,
    image:
      "https://images.unsplash.com/photo-1600891964092-4316c288032e?auto=format&fit=crop&w=800&q=80",
  },

  {
    id: "item-129",
    name: "Pork Fry Sadeko",
    description: "Crispy fried pork tossed with Nepali spices and herbs",
    price: 375,
    categoryId: "cat-9",
    isAvailable: true,
    status: "available",
    preparationTime: 20,
    tags: ["pork", "fried"],
    tax: 13,
    costPrice: 160,
    image:
      "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80",
  },

  {
    id: "item-130",
    name: "Buff Choila",
    description:
      "Traditional grilled buffalo meat mixed with mustard oil and spices",
    price: 275,
    categoryId: "cat-9",
    isAvailable: true,
    status: "available",
    preparationTime: 15,
    tags: ["buff", "choila", "grilled"],
    tax: 13,
    costPrice: 120,
    image:
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80",
  },

  {
    id: "item-131",
    name: "Buff Noodles",
    description: "Stir-fried noodles with buffalo meat and vegetables",
    price: 225,
    categoryId: "cat-9",
    isAvailable: true,
    status: "available",
    preparationTime: 12,
    tags: ["buff", "noodles"],
    tax: 13,
    costPrice: 90,
    image:
      "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?auto=format&fit=crop&w=800&q=80",
  },

  {
    id: "item-132",
    name: "Buff Thukpa",
    description: "Traditional Himalayan noodle soup with buffalo meat",
    price: 275,
    categoryId: "cat-9",
    isAvailable: true,
    status: "available",
    preparationTime: 15,
    tags: ["buff", "thukpa", "soup"],
    tax: 13,
    costPrice: 110,
    image:
      "https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=800&q=80",
  },

  {
    id: "item-133",
    name: "Pork Noodles",
    description: "Stir-fried noodles with pork and fresh vegetables",
    price: 225,
    categoryId: "cat-9",
    isAvailable: true,
    status: "available",
    preparationTime: 12,
    tags: ["pork", "noodles"],
    tax: 13,
    costPrice: 90,
    image:
      "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80",
  },

  {
    id: "item-134",
    name: "Pork Thukpa",
    description: "Warm Himalayan noodle soup prepared with pork and vegetables",
    price: 275,
    categoryId: "cat-9",
    isAvailable: true,
    status: "available",
    preparationTime: 15,
    tags: ["pork", "thukpa", "soup"],
    tax: 13,
    costPrice: 110,
    image:
      "https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=800&q=80",
  },
  // BURGER & SANDWICH
  {
    id: "item-135",
    name: "Veg Burger",
    description: "Fresh vegetable patty burger with lettuce and sauce",
    price: 225,
    categoryId: "cat-7",
    image:
      "https://images.unsplash.com/photo-1520072959219-c595dc870360?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 15,
    tags: ["burger", "vegetarian"],
    tax: 13,
    costPrice: 95,
  },
  {
    id: "item-136",
    name: "Chicken Burger",
    description: "Juicy chicken burger with fresh vegetables",
    price: 250,
    categoryId: "cat-7",
    image:
      "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 18,
    tags: ["burger", "non-veg"],
    tax: 13,
    costPrice: 110,
  },
  {
    id: "item-137",
    name: "Chicken Crispy Burger",
    description: "Crispy fried chicken burger with special sauce",
    price: 300,
    categoryId: "cat-7",
    image:
      "https://images.unsplash.com/photo-1550317138-10000687a72b?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 20,
    tags: ["burger", "crispy", "non-veg"],
    tax: 13,
    costPrice: 130,
  },
  {
    id: "item-138",
    name: "Veg Sandwich",
    description: "Fresh vegetable sandwich with cheese and sauce",
    price: 175,
    categoryId: "cat-7",
    image:
      "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 12,
    tags: ["sandwich", "vegetarian"],
    tax: 13,
    costPrice: 75,
  },
  {
    id: "item-139",
    name: "Chicken Sandwich",
    description: "Chicken sandwich with fresh vegetables",
    price: 200,
    categoryId: "cat-7",
    image:
      "https://images.unsplash.com/photo-1539252554453-80ab65ce3586?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 15,
    tags: ["sandwich", "non-veg"],
    tax: 13,
    costPrice: 85,
  },
  {
    id: "item-140",
    name: "Grilled Chicken Sandwich",
    description: "Grilled chicken sandwich with cheese and vegetables",
    price: 300,
    categoryId: "cat-16",
    image:
      "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 18,
    tags: ["sandwich", "grilled", "non-veg"],
    tax: 13,
    costPrice: 130,
  },

  // ROLLS & WRAPS
  {
    id: "item-141",
    name: "Chicken Katti Roll",
    description: "Nepali-style chicken katti roll with vegetables",
    price: 175,
    categoryId: "cat-8",
    image:
      "https://static.vecteezy.com/system/resources/previews/066/277/664/large_2x/a-plate-of-chicken-kathi-roll-with-chicken-cooked-with-spices-and-wrapped-in-a-paratha-isolated-on-photo.jpg",
    isAvailable: true,
    status: "available",
    preparationTime: 15,
    tags: ["roll", "non-veg"],
    tax: 13,
    costPrice: 75,
  },
  {
    id: "item-142",
    name: "Paneer Katti Roll",
    description: "Paneer-filled katti roll with vegetables and sauce",
    price: 200,
    categoryId: "cat-8",
    image:
      "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 15,
    tags: ["roll", "vegetarian"],
    tax: 13,
    costPrice: 85,
  },
  {
    id: "item-143",
    name: "Chicken Wrap",
    description: "Soft tortilla wrap filled with chicken and vegetables",
    price: 150,
    categoryId: "cat-8",
    image:
      "https://images.unsplash.com/photo-1530469912745-a215c6b256ea?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 12,
    tags: ["wrap", "non-veg"],
    tax: 13,
    costPrice: 65,
  },
  {
    id: "item-144",
    name: "Sausage Wrap",
    description: "Tortilla wrap stuffed with sausage and vegetables",
    price: 150,
    categoryId: "cat-8",
    image:
      "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80",
    isAvailable: true,
    status: "available",
    preparationTime: 12,
    tags: ["wrap"],
    tax: 13,
    costPrice: 65,
  },
];